name: Deploy Website

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Jekyll
        run: gem install jekyll bundler
      - name: Build the site
        run: |
          cd 'blog website xps1'
          bundle init
          echo "gem 'github-pages', group: :jekyll_plugins" >> Gemfile
          bundle install
          bundle exec jekyll build -d ../public
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
